# Email SMTP Configurations
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

# Compatibility settings for Java 17+ / SSL handshake issues
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.ssl.trust=smtp.gmail.com

# Replace with your actual email and Gmail App Password
mail.smtp.user=your-email@gmail.com
mail.smtp.password=your-app-password
